spring.application.name=product-command

server.port=8081

spring.cloud.function.definition=handlerCommands
spring.cloud.stream.bindings.handlerCommands-in-0.destination=products.commands
spring.cloud.stream.bindings.handlerCommands-in-0.contentType=application/json
spring.cloud.stream.bindings.handlerCommands-in-0.group=product-group
spring.cloud.stream.bindings.handlerCommands-in-0.startOffset=latest

spring.cloud.stream.bindings.handlerCommands-out-0.destination=products.replies
spring.cloud.stream.bindings.handlerCommands-out-0.contentType=application/json

spring.cloud.stream.kafka.binder.brokers=localhost:9092

spring.datasource.url=jdbc:mysql://localhost:3306/products_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
#Next is not recommended for production, but it is useful for development and testing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
